== Compile programs optimized for Zen using nix

Contains facilities for installing programs on https://nixos.org/[Nix-based] *Linux* systems with an AMD Ryzen CPU.

The intended use of it is through an "alternative" `pkgs` from the system like:

[source,nix]
----
# Where this would be your regular one
pkgs = import <nixpkgs> {};

# There can be an additional
pkgsTuned = import ./zen-optimized-pkgs.nix {
    inherit  lib;
    importablePkgsDelegate = <nixpkgs>;
    amdZenVersion = 2;
    ltoLevel = "thin"; };
----

The mechanism tries to use the (unoptimized) compilers present on the system and create optimized binaries from the packages to install.

CAUTION:: I'm no expert in this so the approaches may be unorthodox or not work properly.
    I've added some tests which seem to work, though.

=== Covered languages

The implementation covers the following languages:

[cols="1,3,1"]
|===
|Language |Mechanism |Status

| C         | Wrapper -script around system `gcc`       | ✅ tests pass - #double check#
| C++       | Wrapper -script around system `gcc`       | ✅ tests pass - #double check#
| Go        |                                           | ❌ #Compile error#, tests disabled
| Rust      |                                           | ❌ #Compile error#, tests disabled
| Python 3  | Interpreter compiled with optimizations   | ❌ #Compile error#, tests disabled
| Fortran   | Wrapper -script around system `gfortran`  | ✅ tests pass
| Haskell   |                                           | ❌ #Compile error#, #not idiomatic nix#
| Julia     |                                           | ❌ #Compile error#, tests disabled
| R         |                                           | ❌ #Compile error#, need to update test-assertions
| Zig       |                                           | ❌ #Compile error#, #test is bullshit#
|===

=== Open work

* Properly use `lto`
* Use the _ROCM_ packages
* OpenMP - https://github.com/NixOS/nixpkgs/issues/79818

=== Run tests

Tests compile simple programs (xref:test/example-programs/README.adoc[]) in the individual languages and inspect their output.
To execute all the tests run:

[source,shell]
----
nix run --no-write-lock-file github:nix-community/nix-unit -- ./zen-optimized-pkgs.test.nix
----


