== Compile programs optimized for Zen using nix

Contains facilities for installing programs on https://nixos.org/[Nix-based] *Linux* systems with an AMD Ryzen CPU.

----
⚠⚠⚠ The repo is currently *mostly broken* ⚠⚠⚠
----

The intended use of it is through an "alternative" `pkgs` from the system like:

[source,nix]
----
# Where this would be your regular one
pkgs = import <nixpkgs> {};

# There can be an additional
pkgsTuned = import ./zen-optimized-pkgs.nix {
    inherit  lib;
    importablePkgsDelegate = <nixpkgs>;
    amdZenVersion = 2;
    ltoLevel = "thin"; };
----

The mechanism tries to use the (unoptimized) compilers present on the system and create optimized binaries from the packages to install.

CAUTION:: I'm no expert in this so the approaches may be unorthodox or not work properly.
    I've added some tests which seem to work, though.

=== Covered languages

The implementation covers the following languages:

[cols="1,3,2"]
|===
|Language |Mechanism |Status

| C                     | Wrapper-script around system `gcc`        a|
* [yellow]#⚠# Not all optimizations applied properly
* ✅ tests pass - #double check#
| C++                   | Wrapper-script around system `gcc`        a|
* [yellow]#⚠# Not all optimizations applied properly
* ✅ tests pass - #double check#
| Go                    |                                           | ❌ #Compile error#, tests disabled
| Rust                  | Wrapper-script around system `rustc` and `cargo` a|
* ✅ tests pass
| Python 3 (minimal)    | Interpreter compiled with optimizations   a|
* [yellow]#⚠# Should prefer local build because of optimizations
* ✅ tests pass
* [yellow]#⚠# Tests should be more specific on optimizations
| Fortran               | Wrapper-script around system `gfortran`   a|
* ✅ tests pass
| Haskell               |                                           | ❌ #Compile error#, #not idiomatic nix#
| Julia                 |                                           | ❌ #Compile error#, tests disabled
| R                     |                                           | ❌ #Compile error#, need to update test-assertions
| Zig                   |                                           | ❌ #Compile error#, #test is bullshit#
|===

=== Open work

* Properly use `lto`
* Use the _ROCM_ packages
** See also: https://github.com/NixOS/nixpkgs/blob/60a2d618f68142e2e697a7cec22c33212751d73a/pkgs/development/rocm-modules/6/llvm/default.nix#L182
* OpenMP - https://github.com/NixOS/nixpkgs/issues/79818
* _gcc_ (and _binutils_) still seems to be built once I use Python :(
* Use AMD BLIS/LIBFLAME (optimized for modern AMD x86_64 CPUs): +
The AMD fork of the BLIS library, with attribute amd-blis, extends BLIS with optimizations for modern AMD CPUs. The changes are usually submitted to the upstream BLIS project after some time. However, AMD BLIS typically provides some performance improvements on AMD Zen CPUs. The complementary AMD LIBFLAME library, with attribute amd-libflame, provides a LAPACK implementation.
* Set default-args to the Python interpreter - like `-OO` `-X no_debug_ranges`
* Don't build the bootstrap-packages

=== Run tests

Tests compile simple programs (xref:test/example-programs/README.adoc[]) in the individual languages and inspect their output.
To execute all the tests run:

[source,shell]
----
nix run --no-write-lock-file github:nix-community/nix-unit -- ./zen-optimized-pkgs.test.nix
----

==== Simple execute C-Compiler

[source,bash]
----
nix-build -E 'with import ./zen-optimized-pkgs.nix {}; callPackage ./test/example-programs/buildinfo-c/default.nix {}'
./result/bin/buildinfo
----

[source,bash]
----
nix-build -E 'with import ./zen-optimized-pkgs.nix {}; callPackage ./test/example-programs/buildinfo-fortran/default.nix {}'
----